#pragma once
#include <SFML/Graphics.hpp>
#include <SFML/Window.hpp>
#include <SFML/Audio/Sound.hpp>
#include <SFML/Audio/SoundBuffer.hpp>
#include <windows.h>
#include <commdlg.h>
#include <iostream>
#include <string>
#include <iostream>
#include <algorithm>
#include <cctype>
#include "Button.hpp"
#include "AudioFileHandling.hpp"
#include "ProgressBar.hpp"